[general]
version = "0.1.1"

[problem]
problem_name = "heuri"
objective = "Min"
score_regex = '(?m)^\s*Score\s*=\s*(?P<score>\d+)\s*$'

[test]
start_seed = 0
end_seed = 100
threads = 0
out_dir = "./pahcer"

[[test.compile_steps]]
program = "cargo"
args = [
    "build",
    "--release",
]

[[test.compile_steps]]
program = "rm"
args = [
    "-f",
    "./heuri",
]

[[test.compile_steps]]
program = "mv"
args = [
    "./target/release/heuri",
    "./heuri",
]

[[test.test_steps]]
program = "cargo"
args = [
    "run",
    "--bin",
    "tester",
    "--release",
    "../heuri",
]
current_dir = "./tools"
stdin = "./tools/in/{SEED04}.txt"
stdout = "./tools/out/{SEED04}.txt"
stderr = "./tools/err/{SEED04}.txt"
measure_time = true

